<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\packages\EntityFramework.6.4.4\build\EntityFramework.props" Condition="Exists('..\packages\EntityFramework.6.4.4\build\EntityFramework.props')" />
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>C:\Users\Xavier\9TapApplication\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ProductName>9Tap Application</ProductName>
    <PublisherName>CPTC CPW 205</PublisherName>
    <ApplicationRevision>39</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>88E5AF63DE6CF195FD50D36ECEE6E7AD0268860F</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>NineTapTour_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>false</SignManifests>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>9tap_white.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.Linq" />
  </ItemGroup>
  <ItemGroup>
    <None Update="App.Debug.config">
      <DependentUpon>App.config</DependentUpon>
    </None>
    <None Update="App.Release.config">
      <DependentUpon>App.config</DependentUpon>
    </None>
    <Content Include="9tap_white.ico" />
    <Content Include="Database\DBScripts\ninetapdata.sql" />
    <Content Include="Resources\TournamentResultsTemplate.xls">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="Resources\9tapUserManual.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SeriesReportTemplate.xls">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="_NineTapTour_NineTapDbDataSet.xsc">
      <DependentUpon>_NineTapTour_NineTapDbDataSet.xsd</DependentUpon>
    </None>
    <None Update="_NineTapTour_NineTapDbDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>_NineTapTour_NineTapDbDataSet.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </None>
    <None Update="_NineTapTour_NineTapDbDataSet.xss">
      <DependentUpon>_NineTapTour_NineTapDbDataSet.xsd</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\9tap.gif" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.5">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.5 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.SqlServer.Express.11.0">
      <Visible>False</Visible>
      <ProductName>SQL Server 2012 Express</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="VBIDE">
      <Guid>{0002E157-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>5</VersionMajor>
      <VersionMinor>3</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Icon\9tap.ico" />
    <Content Include="Resources\BowlingPin1.png" />
    <Content Include="Resources\9taplogo1.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.2.220602">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.2" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1000" />
    <PackageReference Include="System.Linq.Dynamic.Library" Version="1.1.14" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Database\ParticipantDB.cs" />
    <Compile Remove="Exceptions\GameTableException.cs" />
    <Compile Remove="Exceptions\ParticipantTableException.cs" />
    <Compile Remove="Forms\frmListTournamentsByYear.cs" />
    <Compile Remove="Forms\frmListTournamentsByYear.Designer.cs" />
    <Compile Remove="Forms\FrmTournaments.cs" />
    <Compile Remove="Forms\FrmTournaments.Designer.cs" />
    <Compile Remove="Migrations\201907012231298_test.cs" />
    <Compile Remove="Migrations\201907012231298_test.Designer.cs" />
    <Compile Remove="Migrations\201907012236380_migrationtest.cs" />
    <Compile Remove="Migrations\201907012236380_migrationtest.Designer.cs" />
    <Compile Remove="Migrations\201907012244372_add-migration0619.cs" />
    <Compile Remove="Migrations\201907012244372_add-migration0619.Designer.cs" />
    <EmbeddedResource Remove="Form1.resx" />
    <EmbeddedResource Remove="Forms\frmListTournamentsByYear.resx" />
    <EmbeddedResource Remove="Forms\FrmTournaments.resx" />
    <EmbeddedResource Remove="Migrations\201907012231298_test.resx" />
    <EmbeddedResource Remove="Migrations\201907012236380_migrationtest.resx" />
    <EmbeddedResource Remove="Migrations\201907012244372_add-migration0619.resx" />
  </ItemGroup>
  <UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" />
  <Target Name="AfterCompile" Condition="Exists('App.$(Configuration).config')">
    <TransformXml Source="App.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="App.$(Configuration).config" />
    <ItemGroup>
      <AppConfigWithTargetPath Remove="App.config" />
      <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
        <TargetPath>$(TargetFileName).config</TargetPath>
      </AppConfigWithTargetPath>
    </ItemGroup>
  </Target>
  <Target Name="AfterPublish">
    <PropertyGroup>
      <DeployedConfig>$(_DeploymentApplicationDir)$(TargetName)$(TargetExt).config$(_DeploymentFileMappingExtension)</DeployedConfig>
    </PropertyGroup>
    <Copy Condition="Exists('$(DeployedConfig)')" SourceFiles="$(IntermediateOutputPath)$(TargetFileName).config" DestinationFiles="$(DeployedConfig)" />
  </Target>
  <Import Project="..\packages\EntityFramework.6.4.4\build\EntityFramework.targets" Condition="Exists('..\packages\EntityFramework.6.4.4\build\EntityFramework.targets')" />
</Project>