<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>9tap_white.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Update="App.Debug.config">
      <DependentUpon>App.config</DependentUpon>
    </None>
    <None Update="App.Release.config">
      <DependentUpon>App.config</DependentUpon>
    </None>
    <Content Include="9tap_white.ico" />
    <Content Include="Database\DBScripts\ninetapdata.sql" />
    <Content Include="Resources\TournamentResultsTemplate.xls">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="Resources\9tapUserManual.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SeriesReportTemplate.xls">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="_NineTapTour_NineTapDbDataSet.xsc">
      <DependentUpon>_NineTapTour_NineTapDbDataSet.xsd</DependentUpon>
    </None>
    <None Update="_NineTapTour_NineTapDbDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>_NineTapTour_NineTapDbDataSet.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </None>
    <None Update="_NineTapTour_NineTapDbDataSet.xss">
      <DependentUpon>_NineTapTour_NineTapDbDataSet.xsd</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\9tap.gif" />
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="VBIDE">
      <Guid>{0002E157-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>5</VersionMajor>
      <VersionMinor>3</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="Microsoft.Office.Interop.Excel">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>9</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>00020813-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Icon\9tap.ico" />
    <Content Include="Resources\BowlingPin1.png" />
    <Content Include="Resources\9taplogo1.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.2.220602">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.2" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Database\ParticipantDB.cs" />
    <Compile Remove="Exceptions\GameTableException.cs" />
    <Compile Remove="Exceptions\ParticipantTableException.cs" />
    <Compile Remove="Forms\frmListTournamentsByYear.cs" />
    <Compile Remove="Forms\frmListTournamentsByYear.Designer.cs" />
    <Compile Remove="Forms\FrmTournaments.cs" />
    <Compile Remove="Forms\FrmTournaments.Designer.cs" />
    <Compile Remove="Migrations\201907012231298_test.cs" />
    <Compile Remove="Migrations\201907012231298_test.Designer.cs" />
    <Compile Remove="Migrations\201907012236380_migrationtest.cs" />
    <Compile Remove="Migrations\201907012236380_migrationtest.Designer.cs" />
    <Compile Remove="Migrations\201907012244372_add-migration0619.cs" />
    <Compile Remove="Migrations\201907012244372_add-migration0619.Designer.cs" />
    <EmbeddedResource Remove="Form1.resx" />
    <EmbeddedResource Remove="Forms\frmListTournamentsByYear.resx" />
    <EmbeddedResource Remove="Forms\FrmTournaments.resx" />
    <EmbeddedResource Remove="Migrations\201907012231298_test.resx" />
    <EmbeddedResource Remove="Migrations\201907012236380_migrationtest.resx" />
    <EmbeddedResource Remove="Migrations\201907012244372_add-migration0619.resx" />
  </ItemGroup>
  <UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" />
  <Target Name="AfterCompile" Condition="Exists('App.$(Configuration).config')">
    <TransformXml Source="App.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="App.$(Configuration).config" />
    <ItemGroup>
      <AppConfigWithTargetPath Remove="App.config" />
      <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
        <TargetPath>$(TargetFileName).config</TargetPath>
      </AppConfigWithTargetPath>
    </ItemGroup>
  </Target>
</Project>