// <auto-generated />
namespace NineTapTour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedlistofscores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedlistofscores));
        
        string IMigrationMetadata.Id
        {
            get { return "201510212018305_Added list of scores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
