// <auto-generated />
namespace NineTapTour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Game123arenullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Game123arenullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201512162014146_Game123 are nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
