// <auto-generated />
namespace NineTapTour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SSNLengthChange9to11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SSNLengthChange9to11));
        
        string IMigrationMetadata.Id
        {
            get { return "201512022241424_SSN Length Change 9 to 11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
