// <auto-generated />
namespace NineTapTour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MemberPaymentStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberPaymentStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201605050259447_MemberPaymentStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
