// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NineTapTour.Database;

#nullable disable

namespace NineTapTour.Migrations
{
    [DbContext(typeof(NineTapDb))]
    [Migration("20241219183355_DBUpdate")]
    partial class DBUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NineTapTour.Models.FinalizeTemp", b =>
                {
                    b.Property<int>("FinalizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinalizeID"));

                    b.Property<int>("AdjustedAvg")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<int>("FinalizeRegionID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Game1")
                        .HasColumnType("int");

                    b.Property<int?>("Game2")
                        .HasColumnType("int");

                    b.Property<int?>("Game3")
                        .HasColumnType("int");

                    b.Property<int?>("Game4")
                        .HasColumnType("int");

                    b.Property<int>("GameAvg")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Handicap")
                        .HasColumnType("int");

                    b.Property<int>("HandicapTotal")
                        .HasColumnType("int");

                    b.Property<bool>("KeepAdjustedAvg")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LeagueAverage")
                        .HasColumnType("float");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("MemberNumber")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScratchTotal")
                        .HasColumnType("int");

                    b.Property<int>("Squad")
                        .HasColumnType("int");

                    b.Property<int>("TournamentID")
                        .HasColumnType("int");

                    b.Property<bool>("UseGame1")
                        .HasColumnType("bit");

                    b.Property<bool>("UseGame2")
                        .HasColumnType("bit");

                    b.Property<bool>("UseGame3")
                        .HasColumnType("bit");

                    b.Property<bool>("UseGame4")
                        .HasColumnType("bit");

                    b.HasKey("FinalizeID");

                    b.HasIndex("FinalizeRegionID");

                    b.HasIndex("GameId");

                    b.ToTable("FinalizeTemps", (string)null);
                });

            modelBuilder.Entity("NineTapTour.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bonus")
                        .HasColumnType("int");

                    b.Property<int?>("Game1")
                        .HasColumnType("int");

                    b.Property<int?>("Game2")
                        .HasColumnType("int");

                    b.Property<int?>("Game3")
                        .HasColumnType("int");

                    b.Property<int?>("Game4")
                        .HasColumnType("int");

                    b.Property<int?>("Handicap")
                        .HasColumnType("int");

                    b.Property<int?>("InputtedAvg")
                        .HasColumnType("int");

                    b.Property<bool>("IsComp")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MoneyWon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaceStanding")
                        .HasColumnType("int");

                    b.Property<decimal?>("SidePot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("UseGame1")
                        .HasColumnType("bit");

                    b.Property<bool?>("UseGame2")
                        .HasColumnType("bit");

                    b.Property<bool?>("UseGame3")
                        .HasColumnType("bit");

                    b.Property<bool?>("UseGame4")
                        .HasColumnType("bit");

                    b.Property<int>("gameRegionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NineTapTour.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Average")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("Handicap")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLifetimeMember")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSenior")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastBowled")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPayment")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MoneyEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NineTapRegionID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Referrals")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SSN")
                        .HasMaxLength(11)
                        .HasColumnType("char");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartAvg")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NineTapRegionID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("NineTapTour.Models.NineTapRegion", b =>
                {
                    b.Property<int>("NineTapRegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NineTapRegionID"));

                    b.Property<string>("NineTapRegionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NineTapRegionID");

                    b.ToTable("NineTapRegions", (string)null);
                });

            modelBuilder.Entity("NineTapTour.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantRegionID")
                        .HasColumnType("int");

                    b.Property<int>("Squad")
                        .HasColumnType("int")
                        .HasColumnName("SquadNumber");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MemberId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("NineTapTour.Models.PlayerHistory", b =>
                {
                    b.Property<int>("hisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hisID"));

                    b.Property<int>("AVG")
                        .HasColumnType("int");

                    b.Property<double>("AverageForEntry")
                        .HasColumnType("float");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<int?>("Game1")
                        .HasColumnType("int");

                    b.Property<int?>("Game2")
                        .HasColumnType("int");

                    b.Property<int?>("Game3")
                        .HasColumnType("int");

                    b.Property<int?>("Game4")
                        .HasColumnType("int");

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("HandiCap")
                        .HasColumnType("int");

                    b.Property<int>("MemberNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("MoneyWon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPHG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProPot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("TournamentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("regionID")
                        .HasColumnType("int");

                    b.Property<double>("trueAVG")
                        .HasColumnType("float");

                    b.HasKey("hisID");

                    b.HasIndex("GameID");

                    b.HasIndex("regionID");

                    b.ToTable("PlayerHistories", (string)null);
                });

            modelBuilder.Entity("NineTapTour.Models.Squad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("NineTapTour.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Doubles")
                        .HasColumnType("bit");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnlyThreeGames")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTournamentFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sponsors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Squads")
                        .HasColumnType("int");

                    b.Property<bool>("ThreeOutOf4")
                        .HasColumnType("bit");

                    b.Property<int>("TourneyRegion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("NineTapTour.Models.FinalizeTemp", b =>
                {
                    b.HasOne("NineTapTour.Models.NineTapRegion", "FinalizeRegion")
                        .WithMany()
                        .HasForeignKey("FinalizeRegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NineTapTour.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalizeRegion");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NineTapTour.Models.Member", b =>
                {
                    b.HasOne("NineTapTour.Models.NineTapRegion", "NineTapRegion")
                        .WithMany()
                        .HasForeignKey("NineTapRegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NineTapRegion");
                });

            modelBuilder.Entity("NineTapTour.Models.Participant", b =>
                {
                    b.HasOne("NineTapTour.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("NineTapTour.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NineTapTour.Models.Tournament", "Tournament")
                        .WithMany("Participant")
                        .HasForeignKey("TournamentId");

                    b.Navigation("Game");

                    b.Navigation("Member");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("NineTapTour.Models.PlayerHistory", b =>
                {
                    b.HasOne("NineTapTour.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NineTapTour.Models.NineTapRegion", "NineTapRegion")
                        .WithMany()
                        .HasForeignKey("regionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("NineTapRegion");
                });

            modelBuilder.Entity("NineTapTour.Models.Squad", b =>
                {
                    b.HasOne("NineTapTour.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("NineTapTour.Models.Tournament", b =>
                {
                    b.Navigation("Participant");
                });
#pragma warning restore 612, 618
        }
    }
}
