// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NineTapTour.Core.Data;

#nullable disable

namespace NineTapTour.Core.Data.Migrations
{
    [DbContext(typeof(NineTapDb))]
    [Migration("20260601200157_AddPlaceStandingLabelForTwoDayGroups")]
    partial class AddPlaceStandingLabelForTwoDayGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NineTapTour.Core.Entities.DoublesPartnerClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartnerMemberId")
                        .HasColumnType("int");

                    b.Property<int>("SourceMemberId")
                        .HasColumnType("int");

                    b.Property<int>("Squad")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerMemberId");

                    b.HasIndex("SourceMemberId");

                    b.HasIndex("TournamentId", "SourceMemberId", "PartnerMemberId", "Squad")
                        .IsUnique();

                    b.ToTable("DoublesPartnerClaims");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.DoublesPartnerPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpectedPartnerCount")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Squad")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TournamentId", "MemberId", "Squad")
                        .IsUnique();

                    b.ToTable("DoublesPartnerPlans");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.DoublesTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Member1Id")
                        .HasColumnType("int");

                    b.Property<int>("Member2Id")
                        .HasColumnType("int");

                    b.Property<int>("Squad")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Member1Id");

                    b.HasIndex("Member2Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("DoublesTeams");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustedAvg")
                        .HasColumnType("int");

                    b.Property<int?>("Bonus")
                        .HasColumnType("int");

                    b.Property<int?>("Game1")
                        .HasColumnType("int");

                    b.Property<int?>("Game2")
                        .HasColumnType("int");

                    b.Property<int?>("Game3")
                        .HasColumnType("int");

                    b.Property<int?>("Game4")
                        .HasColumnType("int");

                    b.Property<int?>("Handicap")
                        .HasColumnType("int");

                    b.Property<int>("HandicapTotal")
                        .HasColumnType("int");

                    b.Property<bool>("IsComp")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<bool>("KeepAdjustedAvg")
                        .HasColumnType("bit");

                    b.Property<double>("LeagueAverage")
                        .HasColumnType("float");

                    b.Property<decimal?>("MoneyWon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaceStanding")
                        .HasColumnType("int");

                    b.Property<string>("PlaceStandingLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SidePot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("UseGame1")
                        .HasColumnType("bit");

                    b.Property<bool?>("UseGame2")
                        .HasColumnType("bit");

                    b.Property<bool?>("UseGame3")
                        .HasColumnType("bit");

                    b.Property<bool?>("UseGame4")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Average")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("Handicap")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLifetimeMember")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSenior")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastBowled")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPayment")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MoneyEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Referrals")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SSN")
                        .HasMaxLength(11)
                        .HasColumnType("char");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Squad")
                        .HasColumnType("int")
                        .HasColumnName("SquadNumber");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasFilter("[GameId] IS NOT NULL");

                    b.HasIndex("MemberId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Doubles")
                        .HasColumnType("bit");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnlyThreeGames")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTournamentFinalized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTwoDay")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sponsors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Squads")
                        .HasColumnType("int");

                    b.Property<bool>("ThreeOutOf4")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.DoublesPartnerClaim", b =>
                {
                    b.HasOne("NineTapTour.Core.Entities.Member", "PartnerMember")
                        .WithMany()
                        .HasForeignKey("PartnerMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NineTapTour.Core.Entities.Member", "SourceMember")
                        .WithMany()
                        .HasForeignKey("SourceMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NineTapTour.Core.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartnerMember");

                    b.Navigation("SourceMember");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.DoublesPartnerPlan", b =>
                {
                    b.HasOne("NineTapTour.Core.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NineTapTour.Core.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.DoublesTeam", b =>
                {
                    b.HasOne("NineTapTour.Core.Entities.Member", "Member1")
                        .WithMany()
                        .HasForeignKey("Member1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NineTapTour.Core.Entities.Member", "Member2")
                        .WithMany()
                        .HasForeignKey("Member2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NineTapTour.Core.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member1");

                    b.Navigation("Member2");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.Participant", b =>
                {
                    b.HasOne("NineTapTour.Core.Entities.Game", "Game")
                        .WithOne("Participant")
                        .HasForeignKey("NineTapTour.Core.Entities.Participant", "GameId");

                    b.HasOne("NineTapTour.Core.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NineTapTour.Core.Entities.Tournament", "Tournament")
                        .WithMany("Participant")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Member");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.Game", b =>
                {
                    b.Navigation("Participant");
                });

            modelBuilder.Entity("NineTapTour.Core.Entities.Tournament", b =>
                {
                    b.Navigation("Participant");
                });
#pragma warning restore 612, 618
        }
    }
}
