// <auto-generated />
namespace Member_Import_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReferralsChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReferralsChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201602082225132_ReferralsChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
